language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-arm-dbt-license-.+'
    - 'android-googletv-license-.+'
    - 'intel-android-extra-license-.+'
    - 'mips-android-sysimage-license-.+'
 components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
script:
    - ./gradlew build check